import type { MasterProfile, Service } from "./api";

export const MOCK_SERVICES: Service[] = [
  { id: "Santexnik", nameUz: "Santexnik", nameRu: "Сантехник", icon: "wrench", category: "home" },
  { id: "Elektrik", nameUz: "Elektrik", nameRu: "Электрик", icon: "zap", category: "home" },
  { id: "Konditsioner", nameUz: "Konditsioner", nameRu: "Кондиционер", icon: "wind", category: "home" },
  { id: "Mebel yig'ish", nameUz: "Mebel yig'ish", nameRu: "Сборка мебели", icon: "sofa", category: "home" },
  { id: "Tozalash", nameUz: "Tozalash", nameRu: "Уборка", icon: "sparkles", category: "home" },
  { id: "Bo'yoqchilik", nameUz: "Bo'yoqchilik", nameRu: "Малярные работы", icon: "paintbrush", category: "home" },
];

function mockPro(
  id: string,
  name: string,
  district: string,
  categoryIds: string[],
  priceMin: number,
  priceMax: number,
  rating: number,
  reviews: number,
  orders: number,
  years: number,
  bio: string,
): MasterProfile {
  return {
    id,
    userId: id,
    bio,
    experienceYears: years,
    serviceCategoryIds: categoryIds,
    priceMin,
    priceMax,
    ratingAvg: rating,
    reviewCount: reviews,
    completedOrders: orders,
    district,
    isApproved: true,
    isPremium: rating >= 4.8,
    portfolioImages: [],
    user: { id, name, phone: "+998900000000", avatarUrl: null },
  };
}

export const MOCK_PROFESSIONALS: MasterProfile[] = [
  mockPro(
    "pro-1",
    "Jamshid Karimov",
    "Yunusobod",
    ["Santexnik"],
    150000,
    300000,
    4.9,
    127,
    340,
    10,
    "10 yillik tajriba. Santexnika va quvurlar bo'yicha mutaxassis.",
  ),
  mockPro(
    "pro-2",
    "Rustam Toshmatov",
    "Chilonzor",
    ["Elektrik"],
    120000,
    250000,
    4.8,
    89,
    210,
    8,
    "Elektr montaj, rozetka va yoritish tizimlari.",
  ),
  mockPro(
    "pro-3",
    "Dilshod Rahimov",
    "Mirzo Ulug'bek",
    ["Konditsioner"],
    200000,
    400000,
    4.7,
    64,
    156,
    6,
    "Konditsioner o'rnatish, to'ldirish va ta'mirlash.",
  ),
  mockPro(
    "pro-4",
    "Aziza Karimova",
    "Yakkasaroy",
    ["Tozalash"],
    80000,
    150000,
    4.9,
    203,
    520,
    5,
    "Uy va ofis chuqur tozalash xizmati.",
  ),
  mockPro(
    "pro-5",
    "Bekzod Mirzayev",
    "Olmazor",
    ["Mebel yig'ish"],
    100000,
    200000,
    4.6,
    45,
    98,
    4,
    "IKEA va boshqa mebel yig'ish — tez va sifatli.",
  ),
  mockPro(
    "pro-6",
    "Sardor Nazarov",
    "Sergeli",
    ["Bo'yoqchilik"],
    180000,
    350000,
    4.8,
    72,
    180,
    12,
    "Devor bo'yash, oboy yopishtirish va pardoz ishlari.",
  ),
];

export const MOCK_DISTRICTS = [
  "Yunusobod",
  "Chilonzor",
  "Mirzo Ulug'bek",
  "Yakkasaroy",
  "Olmazor",
  "Sergeli",
  "Bektemir",
  "Uchtepa",
  "Yashnobod",
  "Mirobod",
];
